# Generated by Django 3.0.5 on 2020-05-25 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='logos')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('price20', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('price50', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('price100', models.DecimalField(decimal_places=0, max_digits=7, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spices.Category')),
            ],
        ),
    ]
