# Generated by Django 3.0.5 on 2020-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0003_auto_20200525_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
