# Generated by Django 3.0.5 on 2020-05-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0004_auto_20200527_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price20',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price50',
        ),
    ]
