# Generated by Django 3.0.5 on 2020-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0008_auto_20200528_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
